### ISSUE TITLE
Consider change the reference link scheme

### ISSUE THREAD

**Issue by dcalvin** [tikv/website#105]
Currently, our reference link scheme (in the style of `../../`) is not compatible with GitHub. So in source files on GitHub, the internal relative links don't work. It's not working locally either so that we cannot test it unless we build the site. 
Plus, it's not so intuitive when the path is complicated.  
Can we make the change to use the same style like TiDB used, for example (`/v3.0/glossary.md#acid`)

**Comment by Hoverbear** [comment]
Great idea!

**Comment by Hoverbear** [comment]
Out of curiosity why would you make changes to the site at all without running the live dev preview server gotten via `make serve`?

It's not intended that users would browse github, either.

**Comment by Hoverbear** [comment]
So part of this `../../`schema was for multi-versioning later we won't need to go update the version in every link.


Do you still want this change?

**Comment by dcalvin** [comment]
> Out of curiosity why would you make changes to the site at all without running the live dev preview server gotten via `make serve`?
> 
> It's not intended that users would browse github, either.

Currently, we are used to previewing in the text editor directly (for example in VSC) before we push. If the preview on the VSC is fine, we consider the file fine. The different parse scheme makes the normal process invalid. (the path schema, and also the linkage between words are all handled differently) What we perceive as fine will be wrong in the live preview or on the website.  From our experience, the one used in TiDB is more universal. This makes our current scheme on TiKV.org counter-intuitive and less friendly, as found out

However, if we do that, we need to update the version number in the link for each different version...

What do you suggest?

**Comment by Hoverbear** [comment]
I suggest you only reference the live preview from `hugo serve` or the makefile. We've already seen that Hugo and the VSC parsers differ and TiKV's site has some functionality normal markdown doesn't support.

You'll also find links which work on the site will be broken on the markdown preview.

**Comment by dcalvin** [comment]
> You'll also find links which work on the site will be broken on the markdown preview.

This makes contribution to documentation not so friendly :(

**Comment by Hoverbear** [comment]
@dcalvin Unfortunately this is a "You can't have your cake and eat it too."

I do not think folks should ever find this repo unless they go looking for it. That's why we put all this effort into having a nice website with rich math, menus, and features like figures. Over time, more of these features will come, and more and more this repo will only be useful for folks *developing* the site, as it is intended.

Every developer who has ever worked with a website or on any even trivial code project is used to needing to run a compile/serve/test step, this is no different, and if they refuse for some reason it's trivial for them to check the *automatically build preview in the PR*. Also consider that you and I are virtually the only people who do make significantly complex edits.

**Comment by tisonkun** [comment]
closed as wontfix
